apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpu-observability.fullname" . }}-alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gpu-observability.componentLabels" (dict "root" . "component" "alertmanager") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9093
      targetPort: http
  selector:
    {{- include "gpu-observability.selectorLabels" (dict "root" . "component" "alertmanager") | nindent 4 }}
