apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpu-observability.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gpu-observability.componentLabels" (dict "root" . "component" "prometheus") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9090
      targetPort: http
  selector:
    {{- include "gpu-observability.selectorLabels" (dict "root" . "component" "prometheus") | nindent 4 }}
