apiVersion: v1
kind: Namespace
metadata:
  name: {{ .AddonInstallNamespace }}
  annotations:
    addon.open-cluster-management.io/deletion-orphan: ""
  labels:
    addon.open-cluster-management.io/namespace: "true"
    app.kubernetes.io/name: gpu-platform-addon
    app.kubernetes.io/managed-by: gpu-platform-addon
