apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .AgentName }}
  namespace: {{ .AddonInstallNamespace }}
  labels:
    app.kubernetes.io/name: gpu-platform-addon
    app.kubernetes.io/component: agent
