package options

import (
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/spf13/pflag"
	"k8s.io/apimachinery/pkg/util/validation"
)

const (
	DefaultAddonName             = "gpu-platform-addon"
	DefaultAgentInstallNamespace = "open-cluster-management-agent-addon"
	DefaultReportInterval        = 15 * time.Second
)

type Manager struct {
	Kubeconfig            string
	AgentImage            string
	AddonName             string
	AgentInstallNamespace string
	ReportInterval        time.Duration
}

type Agent struct {
	HubKubeconfig         string
	ManagedKubeconfig     string
	ClusterName           string
	AddonName             string
	AddonInstallNamespace string
	ReportInterval        time.Duration
}

func ParseManager(args []string) (Manager, error) {
	opts := Manager{
		AddonName:             DefaultAddonName,
		AgentInstallNamespace: DefaultAgentInstallNamespace,
		ReportInterval:        DefaultReportInterval,
	}

	flags := pflag.NewFlagSet("manager", pflag.ContinueOnError)
	flags.SetOutput(io.Discard)
	flags.StringVar(&opts.Kubeconfig, "kubeconfig", "", "Hub kubeconfig path; in-cluster configuration is used when empty.")
	flags.StringVar(&opts.AgentImage, "agent-image", "", "Container image installed on managed clusters.")
	flags.StringVar(&opts.AddonName, "addon-name", opts.AddonName, "OCM add-on name.")
	flags.StringVar(&opts.AgentInstallNamespace, "agent-install-namespace", opts.AgentInstallNamespace, "Namespace used to install the managed-cluster agent.")
	flags.DurationVar(&opts.ReportInterval, "report-interval", opts.ReportInterval, "Inventory reporting interval passed to managed-cluster agents.")
	if err := flags.Parse(args); err != nil {
		return Manager{}, err
	}
	if flags.NArg() != 0 {
		return Manager{}, fmt.Errorf("unexpected positional arguments: %s", strings.Join(flags.Args(), " "))
	}
	if err := opts.Validate(); err != nil {
		return Manager{}, err
	}
	return opts, nil
}

func (o Manager) Validate() error {
	if strings.TrimSpace(o.AgentImage) == "" {
		return fmt.Errorf("--agent-image is required")
	}
	if err := validateDNSSubdomain("--addon-name", o.AddonName); err != nil {
		return err
	}
	if err := validateDNSLabel("--agent-install-namespace", o.AgentInstallNamespace); err != nil {
		return err
	}
	if o.ReportInterval <= 0 {
		return fmt.Errorf("--report-interval must be greater than zero")
	}
	return nil
}

func ParseAgent(args []string) (Agent, error) {
	opts := Agent{
		AddonName:             DefaultAddonName,
		AddonInstallNamespace: DefaultAgentInstallNamespace,
		ReportInterval:        DefaultReportInterval,
	}

	flags := pflag.NewFlagSet("agent", pflag.ContinueOnError)
	flags.SetOutput(io.Discard)
	flags.StringVar(&opts.HubKubeconfig, "hub-kubeconfig", "", "Kubeconfig generated by OCM add-on registration for the hub cluster.")
	flags.StringVar(&opts.ManagedKubeconfig, "managed-kubeconfig", "", "Managed-cluster kubeconfig path; in-cluster configuration is used when empty.")
	flags.StringVar(&opts.ClusterName, "cluster-name", "", "OCM ManagedCluster name and hub namespace.")
	flags.StringVar(&opts.AddonName, "addon-name", opts.AddonName, "OCM add-on name.")
	flags.StringVar(&opts.AddonInstallNamespace, "addon-namespace", opts.AddonInstallNamespace, "Namespace where the agent is installed.")
	flags.DurationVar(&opts.ReportInterval, "report-interval", opts.ReportInterval, "Inventory reporting interval.")
	if err := flags.Parse(args); err != nil {
		return Agent{}, err
	}
	if flags.NArg() != 0 {
		return Agent{}, fmt.Errorf("unexpected positional arguments: %s", strings.Join(flags.Args(), " "))
	}
	if err := opts.Validate(); err != nil {
		return Agent{}, err
	}
	return opts, nil
}

func (o Agent) Validate() error {
	if strings.TrimSpace(o.HubKubeconfig) == "" {
		return fmt.Errorf("--hub-kubeconfig is required")
	}
	if err := validateDNSSubdomain("--cluster-name", o.ClusterName); err != nil {
		return err
	}
	if err := validateDNSSubdomain("--addon-name", o.AddonName); err != nil {
		return err
	}
	if err := validateDNSLabel("--addon-namespace", o.AddonInstallNamespace); err != nil {
		return err
	}
	if o.ReportInterval <= 0 {
		return fmt.Errorf("--report-interval must be greater than zero")
	}
	return nil
}

func validateDNSSubdomain(flagName, value string) error {
	if problems := validation.IsDNS1123Subdomain(value); len(problems) != 0 {
		return fmt.Errorf("%s must be a valid DNS subdomain: %s", flagName, strings.Join(problems, "; "))
	}
	return nil
}

func validateDNSLabel(flagName, value string) error {
	if problems := validation.IsDNS1123Label(value); len(problems) != 0 {
		return fmt.Errorf("%s must be a valid DNS label: %s", flagName, strings.Join(problems, "; "))
	}
	return nil
}
